/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the TenantStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantStats{}

// TenantStats Provide operational stats for Tenant
type TenantStats struct {
	Instance NullableInstanceCountByStatus `json:"instance,omitempty"`
	Vpc      NullableVpcCountByStatus      `json:"vpc,omitempty"`
	Subnet   NullableSubnetCountByStatus   `json:"subnet,omitempty"`
}

// NewTenantStats instantiates a new TenantStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantStats() *TenantStats {
	this := TenantStats{}
	return &this
}

// NewTenantStatsWithDefaults instantiates a new TenantStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantStatsWithDefaults() *TenantStats {
	this := TenantStats{}
	return &this
}

// GetInstance returns the Instance field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TenantStats) GetInstance() InstanceCountByStatus {
	if o == nil || IsNil(o.Instance.Get()) {
		var ret InstanceCountByStatus
		return ret
	}
	return *o.Instance.Get()
}

// GetInstanceOk returns a tuple with the Instance field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TenantStats) GetInstanceOk() (*InstanceCountByStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.Instance.Get(), o.Instance.IsSet()
}

// HasInstance returns a boolean if a field has been set.
func (o *TenantStats) HasInstance() bool {
	if o != nil && o.Instance.IsSet() {
		return true
	}

	return false
}

// SetInstance gets a reference to the given NullableInstanceCountByStatus and assigns it to the Instance field.
func (o *TenantStats) SetInstance(v InstanceCountByStatus) {
	o.Instance.Set(&v)
}

// SetInstanceNil sets the value for Instance to be an explicit nil
func (o *TenantStats) SetInstanceNil() {
	o.Instance.Set(nil)
}

// UnsetInstance ensures that no value is present for Instance, not even an explicit nil
func (o *TenantStats) UnsetInstance() {
	o.Instance.Unset()
}

// GetVpc returns the Vpc field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TenantStats) GetVpc() VpcCountByStatus {
	if o == nil || IsNil(o.Vpc.Get()) {
		var ret VpcCountByStatus
		return ret
	}
	return *o.Vpc.Get()
}

// GetVpcOk returns a tuple with the Vpc field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TenantStats) GetVpcOk() (*VpcCountByStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.Vpc.Get(), o.Vpc.IsSet()
}

// HasVpc returns a boolean if a field has been set.
func (o *TenantStats) HasVpc() bool {
	if o != nil && o.Vpc.IsSet() {
		return true
	}

	return false
}

// SetVpc gets a reference to the given NullableVpcCountByStatus and assigns it to the Vpc field.
func (o *TenantStats) SetVpc(v VpcCountByStatus) {
	o.Vpc.Set(&v)
}

// SetVpcNil sets the value for Vpc to be an explicit nil
func (o *TenantStats) SetVpcNil() {
	o.Vpc.Set(nil)
}

// UnsetVpc ensures that no value is present for Vpc, not even an explicit nil
func (o *TenantStats) UnsetVpc() {
	o.Vpc.Unset()
}

// GetSubnet returns the Subnet field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TenantStats) GetSubnet() SubnetCountByStatus {
	if o == nil || IsNil(o.Subnet.Get()) {
		var ret SubnetCountByStatus
		return ret
	}
	return *o.Subnet.Get()
}

// GetSubnetOk returns a tuple with the Subnet field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TenantStats) GetSubnetOk() (*SubnetCountByStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.Subnet.Get(), o.Subnet.IsSet()
}

// HasSubnet returns a boolean if a field has been set.
func (o *TenantStats) HasSubnet() bool {
	if o != nil && o.Subnet.IsSet() {
		return true
	}

	return false
}

// SetSubnet gets a reference to the given NullableSubnetCountByStatus and assigns it to the Subnet field.
func (o *TenantStats) SetSubnet(v SubnetCountByStatus) {
	o.Subnet.Set(&v)
}

// SetSubnetNil sets the value for Subnet to be an explicit nil
func (o *TenantStats) SetSubnetNil() {
	o.Subnet.Set(nil)
}

// UnsetSubnet ensures that no value is present for Subnet, not even an explicit nil
func (o *TenantStats) UnsetSubnet() {
	o.Subnet.Unset()
}

func (o TenantStats) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Instance.IsSet() {
		toSerialize["instance"] = o.Instance.Get()
	}
	if o.Vpc.IsSet() {
		toSerialize["vpc"] = o.Vpc.Get()
	}
	if o.Subnet.IsSet() {
		toSerialize["subnet"] = o.Subnet.Get()
	}
	return toSerialize, nil
}

type NullableTenantStats struct {
	value *TenantStats
	isSet bool
}

func (v NullableTenantStats) Get() *TenantStats {
	return v.value
}

func (v *NullableTenantStats) Set(val *TenantStats) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantStats) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantStats(val *TenantStats) *NullableTenantStats {
	return &NullableTenantStats{value: val, isSet: true}
}

func (v NullableTenantStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
