/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the DpuExtensionServiceObservabilityConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DpuExtensionServiceObservabilityConfig{}

// DpuExtensionServiceObservabilityConfig A single observability configuration for a DPU Extension Service version
type DpuExtensionServiceObservabilityConfig struct {
	// Optional name of the service or component being monitored
	Name       NullableString
	Prometheus NullableDpuExtensionServiceObservabilityPrometheus
	Logging    NullableDpuExtensionServiceObservabilityLogging
}

// NewDpuExtensionServiceObservabilityConfig instantiates a new DpuExtensionServiceObservabilityConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDpuExtensionServiceObservabilityConfig() *DpuExtensionServiceObservabilityConfig {
	this := DpuExtensionServiceObservabilityConfig{}
	return &this
}

// NewDpuExtensionServiceObservabilityConfigWithDefaults instantiates a new DpuExtensionServiceObservabilityConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDpuExtensionServiceObservabilityConfigWithDefaults() *DpuExtensionServiceObservabilityConfig {
	this := DpuExtensionServiceObservabilityConfig{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DpuExtensionServiceObservabilityConfig) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DpuExtensionServiceObservabilityConfig) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *DpuExtensionServiceObservabilityConfig) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *DpuExtensionServiceObservabilityConfig) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *DpuExtensionServiceObservabilityConfig) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *DpuExtensionServiceObservabilityConfig) UnsetName() {
	o.Name.Unset()
}

// GetPrometheus returns the Prometheus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DpuExtensionServiceObservabilityConfig) GetPrometheus() DpuExtensionServiceObservabilityPrometheus {
	if o == nil || IsNil(o.Prometheus.Get()) {
		var ret DpuExtensionServiceObservabilityPrometheus
		return ret
	}
	return *o.Prometheus.Get()
}

// GetPrometheusOk returns a tuple with the Prometheus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DpuExtensionServiceObservabilityConfig) GetPrometheusOk() (*DpuExtensionServiceObservabilityPrometheus, bool) {
	if o == nil {
		return nil, false
	}
	return o.Prometheus.Get(), o.Prometheus.IsSet()
}

// HasPrometheus returns a boolean if a field has been set.
func (o *DpuExtensionServiceObservabilityConfig) HasPrometheus() bool {
	if o != nil && o.Prometheus.IsSet() {
		return true
	}

	return false
}

// SetPrometheus gets a reference to the given NullableDpuExtensionServiceObservabilityPrometheus and assigns it to the Prometheus field.
func (o *DpuExtensionServiceObservabilityConfig) SetPrometheus(v DpuExtensionServiceObservabilityPrometheus) {
	o.Prometheus.Set(&v)
}

// SetPrometheusNil sets the value for Prometheus to be an explicit nil
func (o *DpuExtensionServiceObservabilityConfig) SetPrometheusNil() {
	o.Prometheus.Set(nil)
}

// UnsetPrometheus ensures that no value is present for Prometheus, not even an explicit nil
func (o *DpuExtensionServiceObservabilityConfig) UnsetPrometheus() {
	o.Prometheus.Unset()
}

// GetLogging returns the Logging field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DpuExtensionServiceObservabilityConfig) GetLogging() DpuExtensionServiceObservabilityLogging {
	if o == nil || IsNil(o.Logging.Get()) {
		var ret DpuExtensionServiceObservabilityLogging
		return ret
	}
	return *o.Logging.Get()
}

// GetLoggingOk returns a tuple with the Logging field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DpuExtensionServiceObservabilityConfig) GetLoggingOk() (*DpuExtensionServiceObservabilityLogging, bool) {
	if o == nil {
		return nil, false
	}
	return o.Logging.Get(), o.Logging.IsSet()
}

// HasLogging returns a boolean if a field has been set.
func (o *DpuExtensionServiceObservabilityConfig) HasLogging() bool {
	if o != nil && o.Logging.IsSet() {
		return true
	}

	return false
}

// SetLogging gets a reference to the given NullableDpuExtensionServiceObservabilityLogging and assigns it to the Logging field.
func (o *DpuExtensionServiceObservabilityConfig) SetLogging(v DpuExtensionServiceObservabilityLogging) {
	o.Logging.Set(&v)
}

// SetLoggingNil sets the value for Logging to be an explicit nil
func (o *DpuExtensionServiceObservabilityConfig) SetLoggingNil() {
	o.Logging.Set(nil)
}

// UnsetLogging ensures that no value is present for Logging, not even an explicit nil
func (o *DpuExtensionServiceObservabilityConfig) UnsetLogging() {
	o.Logging.Unset()
}

func (o DpuExtensionServiceObservabilityConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DpuExtensionServiceObservabilityConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Prometheus.IsSet() {
		toSerialize["prometheus"] = o.Prometheus.Get()
	}
	if o.Logging.IsSet() {
		toSerialize["logging"] = o.Logging.Get()
	}
	return toSerialize, nil
}

type NullableDpuExtensionServiceObservabilityConfig struct {
	value *DpuExtensionServiceObservabilityConfig
	isSet bool
}

func (v NullableDpuExtensionServiceObservabilityConfig) Get() *DpuExtensionServiceObservabilityConfig {
	return v.value
}

func (v *NullableDpuExtensionServiceObservabilityConfig) Set(val *DpuExtensionServiceObservabilityConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableDpuExtensionServiceObservabilityConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableDpuExtensionServiceObservabilityConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDpuExtensionServiceObservabilityConfig(val *DpuExtensionServiceObservabilityConfig) *NullableDpuExtensionServiceObservabilityConfig {
	return &NullableDpuExtensionServiceObservabilityConfig{value: val, isSet: true}
}

func (v NullableDpuExtensionServiceObservabilityConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDpuExtensionServiceObservabilityConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
