/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the IpxeScriptArtifact type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IpxeScriptArtifact{}

// IpxeScriptArtifact An artifact (kernel, initrd, ISO, etc.) required by an iPXE OS definition
type IpxeScriptArtifact struct {
	// Artifact identifier referenced by the iPXE template (e.g. kernel, initrd)
	Name string `json:"name"`
	// Remote URL from where the artifact can be retrieved
	Url string `json:"url"`
	// SHA hash of the artifact for integrity verification
	Sha NullableString `json:"sha,omitempty"`
	// Authentication type for the artifact URL (e.g. Basic, Bearer)
	AuthType NullableString `json:"authType,omitempty"`
	// Auth token to retrieve the artifact from the URL
	AuthToken NullableString `json:"authToken,omitempty"`
	// Strategy for caching the artifact on sites
	CacheStrategy string `json:"cacheStrategy"`
}

type _IpxeScriptArtifact IpxeScriptArtifact

// NewIpxeScriptArtifact instantiates a new IpxeScriptArtifact object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIpxeScriptArtifact(name string, url string, cacheStrategy string) *IpxeScriptArtifact {
	this := IpxeScriptArtifact{}
	this.Name = name
	this.Url = url
	this.CacheStrategy = cacheStrategy
	return &this
}

// NewIpxeScriptArtifactWithDefaults instantiates a new IpxeScriptArtifact object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIpxeScriptArtifactWithDefaults() *IpxeScriptArtifact {
	this := IpxeScriptArtifact{}
	return &this
}

// GetName returns the Name field value
func (o *IpxeScriptArtifact) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *IpxeScriptArtifact) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *IpxeScriptArtifact) SetName(v string) {
	o.Name = v
}

// GetUrl returns the Url field value
func (o *IpxeScriptArtifact) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *IpxeScriptArtifact) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *IpxeScriptArtifact) SetUrl(v string) {
	o.Url = v
}

// GetSha returns the Sha field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IpxeScriptArtifact) GetSha() string {
	if o == nil || IsNil(o.Sha.Get()) {
		var ret string
		return ret
	}
	return *o.Sha.Get()
}

// GetShaOk returns a tuple with the Sha field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IpxeScriptArtifact) GetShaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sha.Get(), o.Sha.IsSet()
}

// HasSha returns a boolean if a field has been set.
func (o *IpxeScriptArtifact) HasSha() bool {
	if o != nil && o.Sha.IsSet() {
		return true
	}

	return false
}

// SetSha gets a reference to the given NullableString and assigns it to the Sha field.
func (o *IpxeScriptArtifact) SetSha(v string) {
	o.Sha.Set(&v)
}

// SetShaNil sets the value for Sha to be an explicit nil
func (o *IpxeScriptArtifact) SetShaNil() {
	o.Sha.Set(nil)
}

// UnsetSha ensures that no value is present for Sha, not even an explicit nil
func (o *IpxeScriptArtifact) UnsetSha() {
	o.Sha.Unset()
}

// GetAuthType returns the AuthType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IpxeScriptArtifact) GetAuthType() string {
	if o == nil || IsNil(o.AuthType.Get()) {
		var ret string
		return ret
	}
	return *o.AuthType.Get()
}

// GetAuthTypeOk returns a tuple with the AuthType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IpxeScriptArtifact) GetAuthTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuthType.Get(), o.AuthType.IsSet()
}

// HasAuthType returns a boolean if a field has been set.
func (o *IpxeScriptArtifact) HasAuthType() bool {
	if o != nil && o.AuthType.IsSet() {
		return true
	}

	return false
}

// SetAuthType gets a reference to the given NullableString and assigns it to the AuthType field.
func (o *IpxeScriptArtifact) SetAuthType(v string) {
	o.AuthType.Set(&v)
}

// SetAuthTypeNil sets the value for AuthType to be an explicit nil
func (o *IpxeScriptArtifact) SetAuthTypeNil() {
	o.AuthType.Set(nil)
}

// UnsetAuthType ensures that no value is present for AuthType, not even an explicit nil
func (o *IpxeScriptArtifact) UnsetAuthType() {
	o.AuthType.Unset()
}

// GetAuthToken returns the AuthToken field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IpxeScriptArtifact) GetAuthToken() string {
	if o == nil || IsNil(o.AuthToken.Get()) {
		var ret string
		return ret
	}
	return *o.AuthToken.Get()
}

// GetAuthTokenOk returns a tuple with the AuthToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IpxeScriptArtifact) GetAuthTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuthToken.Get(), o.AuthToken.IsSet()
}

// HasAuthToken returns a boolean if a field has been set.
func (o *IpxeScriptArtifact) HasAuthToken() bool {
	if o != nil && o.AuthToken.IsSet() {
		return true
	}

	return false
}

// SetAuthToken gets a reference to the given NullableString and assigns it to the AuthToken field.
func (o *IpxeScriptArtifact) SetAuthToken(v string) {
	o.AuthToken.Set(&v)
}

// SetAuthTokenNil sets the value for AuthToken to be an explicit nil
func (o *IpxeScriptArtifact) SetAuthTokenNil() {
	o.AuthToken.Set(nil)
}

// UnsetAuthToken ensures that no value is present for AuthToken, not even an explicit nil
func (o *IpxeScriptArtifact) UnsetAuthToken() {
	o.AuthToken.Unset()
}

// GetCacheStrategy returns the CacheStrategy field value
func (o *IpxeScriptArtifact) GetCacheStrategy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CacheStrategy
}

// GetCacheStrategyOk returns a tuple with the CacheStrategy field value
// and a boolean to check if the value has been set.
func (o *IpxeScriptArtifact) GetCacheStrategyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CacheStrategy, true
}

// SetCacheStrategy sets field value
func (o *IpxeScriptArtifact) SetCacheStrategy(v string) {
	o.CacheStrategy = v
}

func (o IpxeScriptArtifact) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IpxeScriptArtifact) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["url"] = o.Url
	if o.Sha.IsSet() {
		toSerialize["sha"] = o.Sha.Get()
	}
	if o.AuthType.IsSet() {
		toSerialize["authType"] = o.AuthType.Get()
	}
	if o.AuthToken.IsSet() {
		toSerialize["authToken"] = o.AuthToken.Get()
	}
	toSerialize["cacheStrategy"] = o.CacheStrategy
	return toSerialize, nil
}

func (o *IpxeScriptArtifact) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"url",
		"cacheStrategy",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIpxeScriptArtifact := _IpxeScriptArtifact{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIpxeScriptArtifact)

	if err != nil {
		return err
	}

	*o = IpxeScriptArtifact(varIpxeScriptArtifact)

	return err
}

type NullableIpxeScriptArtifact struct {
	value *IpxeScriptArtifact
	isSet bool
}

func (v NullableIpxeScriptArtifact) Get() *IpxeScriptArtifact {
	return v.value
}

func (v *NullableIpxeScriptArtifact) Set(val *IpxeScriptArtifact) {
	v.value = val
	v.isSet = true
}

func (v NullableIpxeScriptArtifact) IsSet() bool {
	return v.isSet
}

func (v *NullableIpxeScriptArtifact) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIpxeScriptArtifact(val *IpxeScriptArtifact) *NullableIpxeScriptArtifact {
	return &NullableIpxeScriptArtifact{value: val, isSet: true}
}

func (v NullableIpxeScriptArtifact) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIpxeScriptArtifact) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
