/*
NVIDIA Bare Metal Manager REST API

NVIDIA Bare Metal Manager REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Bare Metal Manager datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PatchRackRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchRackRequest{}

// PatchRackRequest Request body for patching an existing Rack. Only provided fields are updated.
type PatchRackRequest struct {
	// ID of the Site
	SiteId string `json:"siteId"`
	// Updated name of the Rack
	Name *string `json:"name,omitempty"`
	// Updated manufacturer of the Rack
	Manufacturer *string `json:"manufacturer,omitempty"`
	// Updated model of the Rack
	Model *string `json:"model,omitempty"`
	// Updated serial number of the Rack
	SerialNumber *string `json:"serialNumber,omitempty"`
	// Updated description of the Rack
	Description *string `json:"description,omitempty"`
	Location *RackLocation `json:"location,omitempty"`
}

type _PatchRackRequest PatchRackRequest

// NewPatchRackRequest instantiates a new PatchRackRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchRackRequest(siteId string) *PatchRackRequest {
	this := PatchRackRequest{}
	this.SiteId = siteId
	return &this
}

// NewPatchRackRequestWithDefaults instantiates a new PatchRackRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchRackRequestWithDefaults() *PatchRackRequest {
	this := PatchRackRequest{}
	return &this
}

// GetSiteId returns the SiteId field value
func (o *PatchRackRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *PatchRackRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *PatchRackRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PatchRackRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchRackRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PatchRackRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PatchRackRequest) SetName(v string) {
	o.Name = &v
}

// GetManufacturer returns the Manufacturer field value if set, zero value otherwise.
func (o *PatchRackRequest) GetManufacturer() string {
	if o == nil || IsNil(o.Manufacturer) {
		var ret string
		return ret
	}
	return *o.Manufacturer
}

// GetManufacturerOk returns a tuple with the Manufacturer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchRackRequest) GetManufacturerOk() (*string, bool) {
	if o == nil || IsNil(o.Manufacturer) {
		return nil, false
	}
	return o.Manufacturer, true
}

// HasManufacturer returns a boolean if a field has been set.
func (o *PatchRackRequest) HasManufacturer() bool {
	if o != nil && !IsNil(o.Manufacturer) {
		return true
	}

	return false
}

// SetManufacturer gets a reference to the given string and assigns it to the Manufacturer field.
func (o *PatchRackRequest) SetManufacturer(v string) {
	o.Manufacturer = &v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *PatchRackRequest) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchRackRequest) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *PatchRackRequest) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *PatchRackRequest) SetModel(v string) {
	o.Model = &v
}

// GetSerialNumber returns the SerialNumber field value if set, zero value otherwise.
func (o *PatchRackRequest) GetSerialNumber() string {
	if o == nil || IsNil(o.SerialNumber) {
		var ret string
		return ret
	}
	return *o.SerialNumber
}

// GetSerialNumberOk returns a tuple with the SerialNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchRackRequest) GetSerialNumberOk() (*string, bool) {
	if o == nil || IsNil(o.SerialNumber) {
		return nil, false
	}
	return o.SerialNumber, true
}

// HasSerialNumber returns a boolean if a field has been set.
func (o *PatchRackRequest) HasSerialNumber() bool {
	if o != nil && !IsNil(o.SerialNumber) {
		return true
	}

	return false
}

// SetSerialNumber gets a reference to the given string and assigns it to the SerialNumber field.
func (o *PatchRackRequest) SetSerialNumber(v string) {
	o.SerialNumber = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PatchRackRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchRackRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PatchRackRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PatchRackRequest) SetDescription(v string) {
	o.Description = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *PatchRackRequest) GetLocation() RackLocation {
	if o == nil || IsNil(o.Location) {
		var ret RackLocation
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchRackRequest) GetLocationOk() (*RackLocation, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *PatchRackRequest) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given RackLocation and assigns it to the Location field.
func (o *PatchRackRequest) SetLocation(v RackLocation) {
	o.Location = &v
}

func (o PatchRackRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchRackRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Manufacturer) {
		toSerialize["manufacturer"] = o.Manufacturer
	}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.SerialNumber) {
		toSerialize["serialNumber"] = o.SerialNumber
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	return toSerialize, nil
}

func (o *PatchRackRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPatchRackRequest := _PatchRackRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPatchRackRequest)

	if err != nil {
		return err
	}

	*o = PatchRackRequest(varPatchRackRequest)

	return err
}

type NullablePatchRackRequest struct {
	value *PatchRackRequest
	isSet bool
}

func (v NullablePatchRackRequest) Get() *PatchRackRequest {
	return v.value
}

func (v *NullablePatchRackRequest) Set(val *PatchRackRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchRackRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchRackRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchRackRequest(val *PatchRackRequest) *NullablePatchRackRequest {
	return &NullablePatchRackRequest{value: val, isSet: true}
}

func (v NullablePatchRackRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchRackRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


