/*
NVIDIA Bare Metal Manager REST API

NVIDIA Bare Metal Manager REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Bare Metal Manager datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateRackResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRackResponse{}

// CreateRackResponse Response for creating a Rack containing the new rack's ID
type CreateRackResponse struct {
	// ID of the newly created Rack
	Id string `json:"id"`
}

type _CreateRackResponse CreateRackResponse

// NewCreateRackResponse instantiates a new CreateRackResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRackResponse(id string) *CreateRackResponse {
	this := CreateRackResponse{}
	this.Id = id
	return &this
}

// NewCreateRackResponseWithDefaults instantiates a new CreateRackResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRackResponseWithDefaults() *CreateRackResponse {
	this := CreateRackResponse{}
	return &this
}

// GetId returns the Id field value
func (o *CreateRackResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateRackResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateRackResponse) SetId(v string) {
	o.Id = v
}

func (o CreateRackResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRackResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *CreateRackResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateRackResponse := _CreateRackResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateRackResponse)

	if err != nil {
		return err
	}

	*o = CreateRackResponse(varCreateRackResponse)

	return err
}

type NullableCreateRackResponse struct {
	value *CreateRackResponse
	isSet bool
}

func (v NullableCreateRackResponse) Get() *CreateRackResponse {
	return v.value
}

func (v *NullableCreateRackResponse) Set(val *CreateRackResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRackResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRackResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRackResponse(val *CreateRackResponse) *NullableCreateRackResponse {
	return &NullableCreateRackResponse{value: val, isSet: true}
}

func (v NullableCreateRackResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRackResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


