/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the TenantCapabilitiesUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantCapabilitiesUpdateRequest{}

// TenantCapabilitiesUpdateRequest Request data to update Tenant capabilities.  No fields are required; an empty request body will suffice.
type TenantCapabilitiesUpdateRequest struct {
	// When true, enables targeted instance creation (Machine ID) for the Tenant.
	TargetedInstanceCreation *bool `json:"targetedInstanceCreation,omitempty"`
}

// NewTenantCapabilitiesUpdateRequest instantiates a new TenantCapabilitiesUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantCapabilitiesUpdateRequest() *TenantCapabilitiesUpdateRequest {
	this := TenantCapabilitiesUpdateRequest{}
	return &this
}

// NewTenantCapabilitiesUpdateRequestWithDefaults instantiates a new TenantCapabilitiesUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantCapabilitiesUpdateRequestWithDefaults() *TenantCapabilitiesUpdateRequest {
	this := TenantCapabilitiesUpdateRequest{}
	return &this
}

// GetTargetedInstanceCreation returns the TargetedInstanceCreation field value if set, zero value otherwise.
func (o *TenantCapabilitiesUpdateRequest) GetTargetedInstanceCreation() bool {
	if o == nil || IsNil(o.TargetedInstanceCreation) {
		var ret bool
		return ret
	}
	return *o.TargetedInstanceCreation
}

// GetTargetedInstanceCreationOk returns a tuple with the TargetedInstanceCreation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantCapabilitiesUpdateRequest) GetTargetedInstanceCreationOk() (*bool, bool) {
	if o == nil || IsNil(o.TargetedInstanceCreation) {
		return nil, false
	}
	return o.TargetedInstanceCreation, true
}

// HasTargetedInstanceCreation returns a boolean if a field has been set.
func (o *TenantCapabilitiesUpdateRequest) HasTargetedInstanceCreation() bool {
	if o != nil && !IsNil(o.TargetedInstanceCreation) {
		return true
	}

	return false
}

// SetTargetedInstanceCreation gets a reference to the given bool and assigns it to the TargetedInstanceCreation field.
func (o *TenantCapabilitiesUpdateRequest) SetTargetedInstanceCreation(v bool) {
	o.TargetedInstanceCreation = &v
}

func (o TenantCapabilitiesUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantCapabilitiesUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TargetedInstanceCreation) {
		toSerialize["targetedInstanceCreation"] = o.TargetedInstanceCreation
	}
	return toSerialize, nil
}

type NullableTenantCapabilitiesUpdateRequest struct {
	value *TenantCapabilitiesUpdateRequest
	isSet bool
}

func (v NullableTenantCapabilitiesUpdateRequest) Get() *TenantCapabilitiesUpdateRequest {
	return v.value
}

func (v *NullableTenantCapabilitiesUpdateRequest) Set(val *TenantCapabilitiesUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantCapabilitiesUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantCapabilitiesUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantCapabilitiesUpdateRequest(val *TenantCapabilitiesUpdateRequest) *NullableTenantCapabilitiesUpdateRequest {
	return &NullableTenantCapabilitiesUpdateRequest{value: val, isSet: true}
}

func (v NullableTenantCapabilitiesUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantCapabilitiesUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
