/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the SiteMachineStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteMachineStats{}

// SiteMachineStats Machine stats for a Site
type SiteMachineStats struct {
	Total                  *int32                                    `json:"total,omitempty"`
	TotalByStatus          NullableSiteMachineStatsByStatus          `json:"totalByStatus,omitempty"`
	TotalByHealth          NullableSiteMachineStatsByHealth          `json:"totalByHealth,omitempty"`
	TotalByStatusAndHealth NullableSiteMachineStatsByStatusAndHealth `json:"totalByStatusAndHealth,omitempty"`
	TotalByAllocation      NullableSiteMachineStatsByAllocation      `json:"totalByAllocation,omitempty"`
}

// NewSiteMachineStats instantiates a new SiteMachineStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteMachineStats() *SiteMachineStats {
	this := SiteMachineStats{}
	return &this
}

// NewSiteMachineStatsWithDefaults instantiates a new SiteMachineStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteMachineStatsWithDefaults() *SiteMachineStats {
	this := SiteMachineStats{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *SiteMachineStats) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMachineStats) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *SiteMachineStats) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *SiteMachineStats) SetTotal(v int32) {
	o.Total = &v
}

// GetTotalByStatus returns the TotalByStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SiteMachineStats) GetTotalByStatus() SiteMachineStatsByStatus {
	if o == nil || IsNil(o.TotalByStatus.Get()) {
		var ret SiteMachineStatsByStatus
		return ret
	}
	return *o.TotalByStatus.Get()
}

// GetTotalByStatusOk returns a tuple with the TotalByStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SiteMachineStats) GetTotalByStatusOk() (*SiteMachineStatsByStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.TotalByStatus.Get(), o.TotalByStatus.IsSet()
}

// HasTotalByStatus returns a boolean if a field has been set.
func (o *SiteMachineStats) HasTotalByStatus() bool {
	if o != nil && o.TotalByStatus.IsSet() {
		return true
	}

	return false
}

// SetTotalByStatus gets a reference to the given NullableSiteMachineStatsByStatus and assigns it to the TotalByStatus field.
func (o *SiteMachineStats) SetTotalByStatus(v SiteMachineStatsByStatus) {
	o.TotalByStatus.Set(&v)
}

// SetTotalByStatusNil sets the value for TotalByStatus to be an explicit nil
func (o *SiteMachineStats) SetTotalByStatusNil() {
	o.TotalByStatus.Set(nil)
}

// UnsetTotalByStatus ensures that no value is present for TotalByStatus, not even an explicit nil
func (o *SiteMachineStats) UnsetTotalByStatus() {
	o.TotalByStatus.Unset()
}

// GetTotalByHealth returns the TotalByHealth field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SiteMachineStats) GetTotalByHealth() SiteMachineStatsByHealth {
	if o == nil || IsNil(o.TotalByHealth.Get()) {
		var ret SiteMachineStatsByHealth
		return ret
	}
	return *o.TotalByHealth.Get()
}

// GetTotalByHealthOk returns a tuple with the TotalByHealth field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SiteMachineStats) GetTotalByHealthOk() (*SiteMachineStatsByHealth, bool) {
	if o == nil {
		return nil, false
	}
	return o.TotalByHealth.Get(), o.TotalByHealth.IsSet()
}

// HasTotalByHealth returns a boolean if a field has been set.
func (o *SiteMachineStats) HasTotalByHealth() bool {
	if o != nil && o.TotalByHealth.IsSet() {
		return true
	}

	return false
}

// SetTotalByHealth gets a reference to the given NullableSiteMachineStatsByHealth and assigns it to the TotalByHealth field.
func (o *SiteMachineStats) SetTotalByHealth(v SiteMachineStatsByHealth) {
	o.TotalByHealth.Set(&v)
}

// SetTotalByHealthNil sets the value for TotalByHealth to be an explicit nil
func (o *SiteMachineStats) SetTotalByHealthNil() {
	o.TotalByHealth.Set(nil)
}

// UnsetTotalByHealth ensures that no value is present for TotalByHealth, not even an explicit nil
func (o *SiteMachineStats) UnsetTotalByHealth() {
	o.TotalByHealth.Unset()
}

// GetTotalByStatusAndHealth returns the TotalByStatusAndHealth field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SiteMachineStats) GetTotalByStatusAndHealth() SiteMachineStatsByStatusAndHealth {
	if o == nil || IsNil(o.TotalByStatusAndHealth.Get()) {
		var ret SiteMachineStatsByStatusAndHealth
		return ret
	}
	return *o.TotalByStatusAndHealth.Get()
}

// GetTotalByStatusAndHealthOk returns a tuple with the TotalByStatusAndHealth field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SiteMachineStats) GetTotalByStatusAndHealthOk() (*SiteMachineStatsByStatusAndHealth, bool) {
	if o == nil {
		return nil, false
	}
	return o.TotalByStatusAndHealth.Get(), o.TotalByStatusAndHealth.IsSet()
}

// HasTotalByStatusAndHealth returns a boolean if a field has been set.
func (o *SiteMachineStats) HasTotalByStatusAndHealth() bool {
	if o != nil && o.TotalByStatusAndHealth.IsSet() {
		return true
	}

	return false
}

// SetTotalByStatusAndHealth gets a reference to the given NullableSiteMachineStatsByStatusAndHealth and assigns it to the TotalByStatusAndHealth field.
func (o *SiteMachineStats) SetTotalByStatusAndHealth(v SiteMachineStatsByStatusAndHealth) {
	o.TotalByStatusAndHealth.Set(&v)
}

// SetTotalByStatusAndHealthNil sets the value for TotalByStatusAndHealth to be an explicit nil
func (o *SiteMachineStats) SetTotalByStatusAndHealthNil() {
	o.TotalByStatusAndHealth.Set(nil)
}

// UnsetTotalByStatusAndHealth ensures that no value is present for TotalByStatusAndHealth, not even an explicit nil
func (o *SiteMachineStats) UnsetTotalByStatusAndHealth() {
	o.TotalByStatusAndHealth.Unset()
}

// GetTotalByAllocation returns the TotalByAllocation field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SiteMachineStats) GetTotalByAllocation() SiteMachineStatsByAllocation {
	if o == nil || IsNil(o.TotalByAllocation.Get()) {
		var ret SiteMachineStatsByAllocation
		return ret
	}
	return *o.TotalByAllocation.Get()
}

// GetTotalByAllocationOk returns a tuple with the TotalByAllocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SiteMachineStats) GetTotalByAllocationOk() (*SiteMachineStatsByAllocation, bool) {
	if o == nil {
		return nil, false
	}
	return o.TotalByAllocation.Get(), o.TotalByAllocation.IsSet()
}

// HasTotalByAllocation returns a boolean if a field has been set.
func (o *SiteMachineStats) HasTotalByAllocation() bool {
	if o != nil && o.TotalByAllocation.IsSet() {
		return true
	}

	return false
}

// SetTotalByAllocation gets a reference to the given NullableSiteMachineStatsByAllocation and assigns it to the TotalByAllocation field.
func (o *SiteMachineStats) SetTotalByAllocation(v SiteMachineStatsByAllocation) {
	o.TotalByAllocation.Set(&v)
}

// SetTotalByAllocationNil sets the value for TotalByAllocation to be an explicit nil
func (o *SiteMachineStats) SetTotalByAllocationNil() {
	o.TotalByAllocation.Set(nil)
}

// UnsetTotalByAllocation ensures that no value is present for TotalByAllocation, not even an explicit nil
func (o *SiteMachineStats) UnsetTotalByAllocation() {
	o.TotalByAllocation.Unset()
}

func (o SiteMachineStats) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteMachineStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if o.TotalByStatus.IsSet() {
		toSerialize["totalByStatus"] = o.TotalByStatus.Get()
	}
	if o.TotalByHealth.IsSet() {
		toSerialize["totalByHealth"] = o.TotalByHealth.Get()
	}
	if o.TotalByStatusAndHealth.IsSet() {
		toSerialize["totalByStatusAndHealth"] = o.TotalByStatusAndHealth.Get()
	}
	if o.TotalByAllocation.IsSet() {
		toSerialize["totalByAllocation"] = o.TotalByAllocation.Get()
	}
	return toSerialize, nil
}

type NullableSiteMachineStats struct {
	value *SiteMachineStats
	isSet bool
}

func (v NullableSiteMachineStats) Get() *SiteMachineStats {
	return v.value
}

func (v *NullableSiteMachineStats) Set(val *SiteMachineStats) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteMachineStats) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteMachineStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteMachineStats(val *SiteMachineStats) *NullableSiteMachineStats {
	return &NullableSiteMachineStats{value: val, isSet: true}
}

func (v NullableSiteMachineStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteMachineStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
