/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the MachineMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MachineMetadata{}

// MachineMetadata Describes metadata for various Machine components
type MachineMetadata struct {
	DmiData              NullableMachineDMIData       `json:"dmiData,omitempty"`
	BmcInfo              NullableMachineBMCInfo       `json:"bmcInfo,omitempty"`
	Gpus                 []MachineGPUInfo             `json:"gpus,omitempty"`
	NetworkInterfaces    []MachineNetworkInterface    `json:"networkInterfaces,omitempty"`
	InfinibandInterfaces []MachineInfiniBandInterface `json:"infinibandInterfaces,omitempty"`
}

// NewMachineMetadata instantiates a new MachineMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMachineMetadata() *MachineMetadata {
	this := MachineMetadata{}
	return &this
}

// NewMachineMetadataWithDefaults instantiates a new MachineMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMachineMetadataWithDefaults() *MachineMetadata {
	this := MachineMetadata{}
	return &this
}

// GetDmiData returns the DmiData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MachineMetadata) GetDmiData() MachineDMIData {
	if o == nil || IsNil(o.DmiData.Get()) {
		var ret MachineDMIData
		return ret
	}
	return *o.DmiData.Get()
}

// GetDmiDataOk returns a tuple with the DmiData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MachineMetadata) GetDmiDataOk() (*MachineDMIData, bool) {
	if o == nil {
		return nil, false
	}
	return o.DmiData.Get(), o.DmiData.IsSet()
}

// HasDmiData returns a boolean if a field has been set.
func (o *MachineMetadata) HasDmiData() bool {
	if o != nil && o.DmiData.IsSet() {
		return true
	}

	return false
}

// SetDmiData gets a reference to the given NullableMachineDMIData and assigns it to the DmiData field.
func (o *MachineMetadata) SetDmiData(v MachineDMIData) {
	o.DmiData.Set(&v)
}

// SetDmiDataNil sets the value for DmiData to be an explicit nil
func (o *MachineMetadata) SetDmiDataNil() {
	o.DmiData.Set(nil)
}

// UnsetDmiData ensures that no value is present for DmiData, not even an explicit nil
func (o *MachineMetadata) UnsetDmiData() {
	o.DmiData.Unset()
}

// GetBmcInfo returns the BmcInfo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MachineMetadata) GetBmcInfo() MachineBMCInfo {
	if o == nil || IsNil(o.BmcInfo.Get()) {
		var ret MachineBMCInfo
		return ret
	}
	return *o.BmcInfo.Get()
}

// GetBmcInfoOk returns a tuple with the BmcInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MachineMetadata) GetBmcInfoOk() (*MachineBMCInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.BmcInfo.Get(), o.BmcInfo.IsSet()
}

// HasBmcInfo returns a boolean if a field has been set.
func (o *MachineMetadata) HasBmcInfo() bool {
	if o != nil && o.BmcInfo.IsSet() {
		return true
	}

	return false
}

// SetBmcInfo gets a reference to the given NullableMachineBMCInfo and assigns it to the BmcInfo field.
func (o *MachineMetadata) SetBmcInfo(v MachineBMCInfo) {
	o.BmcInfo.Set(&v)
}

// SetBmcInfoNil sets the value for BmcInfo to be an explicit nil
func (o *MachineMetadata) SetBmcInfoNil() {
	o.BmcInfo.Set(nil)
}

// UnsetBmcInfo ensures that no value is present for BmcInfo, not even an explicit nil
func (o *MachineMetadata) UnsetBmcInfo() {
	o.BmcInfo.Unset()
}

// GetGpus returns the Gpus field value if set, zero value otherwise.
func (o *MachineMetadata) GetGpus() []MachineGPUInfo {
	if o == nil || IsNil(o.Gpus) {
		var ret []MachineGPUInfo
		return ret
	}
	return o.Gpus
}

// GetGpusOk returns a tuple with the Gpus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineMetadata) GetGpusOk() ([]MachineGPUInfo, bool) {
	if o == nil || IsNil(o.Gpus) {
		return nil, false
	}
	return o.Gpus, true
}

// HasGpus returns a boolean if a field has been set.
func (o *MachineMetadata) HasGpus() bool {
	if o != nil && !IsNil(o.Gpus) {
		return true
	}

	return false
}

// SetGpus gets a reference to the given []MachineGPUInfo and assigns it to the Gpus field.
func (o *MachineMetadata) SetGpus(v []MachineGPUInfo) {
	o.Gpus = v
}

// GetNetworkInterfaces returns the NetworkInterfaces field value if set, zero value otherwise.
func (o *MachineMetadata) GetNetworkInterfaces() []MachineNetworkInterface {
	if o == nil || IsNil(o.NetworkInterfaces) {
		var ret []MachineNetworkInterface
		return ret
	}
	return o.NetworkInterfaces
}

// GetNetworkInterfacesOk returns a tuple with the NetworkInterfaces field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineMetadata) GetNetworkInterfacesOk() ([]MachineNetworkInterface, bool) {
	if o == nil || IsNil(o.NetworkInterfaces) {
		return nil, false
	}
	return o.NetworkInterfaces, true
}

// HasNetworkInterfaces returns a boolean if a field has been set.
func (o *MachineMetadata) HasNetworkInterfaces() bool {
	if o != nil && !IsNil(o.NetworkInterfaces) {
		return true
	}

	return false
}

// SetNetworkInterfaces gets a reference to the given []MachineNetworkInterface and assigns it to the NetworkInterfaces field.
func (o *MachineMetadata) SetNetworkInterfaces(v []MachineNetworkInterface) {
	o.NetworkInterfaces = v
}

// GetInfinibandInterfaces returns the InfinibandInterfaces field value if set, zero value otherwise.
func (o *MachineMetadata) GetInfinibandInterfaces() []MachineInfiniBandInterface {
	if o == nil || IsNil(o.InfinibandInterfaces) {
		var ret []MachineInfiniBandInterface
		return ret
	}
	return o.InfinibandInterfaces
}

// GetInfinibandInterfacesOk returns a tuple with the InfinibandInterfaces field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MachineMetadata) GetInfinibandInterfacesOk() ([]MachineInfiniBandInterface, bool) {
	if o == nil || IsNil(o.InfinibandInterfaces) {
		return nil, false
	}
	return o.InfinibandInterfaces, true
}

// HasInfinibandInterfaces returns a boolean if a field has been set.
func (o *MachineMetadata) HasInfinibandInterfaces() bool {
	if o != nil && !IsNil(o.InfinibandInterfaces) {
		return true
	}

	return false
}

// SetInfinibandInterfaces gets a reference to the given []MachineInfiniBandInterface and assigns it to the InfinibandInterfaces field.
func (o *MachineMetadata) SetInfinibandInterfaces(v []MachineInfiniBandInterface) {
	o.InfinibandInterfaces = v
}

func (o MachineMetadata) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MachineMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.DmiData.IsSet() {
		toSerialize["dmiData"] = o.DmiData.Get()
	}
	if o.BmcInfo.IsSet() {
		toSerialize["bmcInfo"] = o.BmcInfo.Get()
	}
	if !IsNil(o.Gpus) {
		toSerialize["gpus"] = o.Gpus
	}
	if !IsNil(o.NetworkInterfaces) {
		toSerialize["networkInterfaces"] = o.NetworkInterfaces
	}
	if !IsNil(o.InfinibandInterfaces) {
		toSerialize["infinibandInterfaces"] = o.InfinibandInterfaces
	}
	return toSerialize, nil
}

type NullableMachineMetadata struct {
	value *MachineMetadata
	isSet bool
}

func (v NullableMachineMetadata) Get() *MachineMetadata {
	return v.value
}

func (v *NullableMachineMetadata) Set(val *MachineMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableMachineMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableMachineMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMachineMetadata(val *MachineMetadata) *NullableMachineMetadata {
	return &NullableMachineMetadata{value: val, isSet: true}
}

func (v NullableMachineMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMachineMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
