/*
NVIDIA Bare Metal Manager REST API

NVIDIA Bare Metal Manager REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Bare Metal Manager datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the PatchRackResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchRackResponse{}

// PatchRackResponse Response for patching a Rack
type PatchRackResponse struct {
	// Summary report of changes applied
	Report *string `json:"report,omitempty"`
}

// NewPatchRackResponse instantiates a new PatchRackResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchRackResponse() *PatchRackResponse {
	this := PatchRackResponse{}
	return &this
}

// NewPatchRackResponseWithDefaults instantiates a new PatchRackResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchRackResponseWithDefaults() *PatchRackResponse {
	this := PatchRackResponse{}
	return &this
}

// GetReport returns the Report field value if set, zero value otherwise.
func (o *PatchRackResponse) GetReport() string {
	if o == nil || IsNil(o.Report) {
		var ret string
		return ret
	}
	return *o.Report
}

// GetReportOk returns a tuple with the Report field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchRackResponse) GetReportOk() (*string, bool) {
	if o == nil || IsNil(o.Report) {
		return nil, false
	}
	return o.Report, true
}

// HasReport returns a boolean if a field has been set.
func (o *PatchRackResponse) HasReport() bool {
	if o != nil && !IsNil(o.Report) {
		return true
	}

	return false
}

// SetReport gets a reference to the given string and assigns it to the Report field.
func (o *PatchRackResponse) SetReport(v string) {
	o.Report = &v
}

func (o PatchRackResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchRackResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Report) {
		toSerialize["report"] = o.Report
	}
	return toSerialize, nil
}

type NullablePatchRackResponse struct {
	value *PatchRackResponse
	isSet bool
}

func (v NullablePatchRackResponse) Get() *PatchRackResponse {
	return v.value
}

func (v *NullablePatchRackResponse) Set(val *PatchRackResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchRackResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchRackResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchRackResponse(val *PatchRackResponse) *NullablePatchRackResponse {
	return &NullablePatchRackResponse{value: val, isSet: true}
}

func (v NullablePatchRackResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchRackResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


