/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the MachineInstanceTypeSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MachineInstanceTypeSummary{}

// MachineInstanceTypeSummary Summary of machines grouped by assigned vs unassigned instance type
type MachineInstanceTypeSummary struct {
	// Machines that have been assigned to an instance type
	Assigned NullableMachineStatusBreakdown `json:"assigned,omitempty"`
	// Machines that have not been assigned to any instance type
	Unassigned NullableMachineStatusBreakdown `json:"unassigned,omitempty"`
}

// NewMachineInstanceTypeSummary instantiates a new MachineInstanceTypeSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMachineInstanceTypeSummary() *MachineInstanceTypeSummary {
	this := MachineInstanceTypeSummary{}
	return &this
}

// NewMachineInstanceTypeSummaryWithDefaults instantiates a new MachineInstanceTypeSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMachineInstanceTypeSummaryWithDefaults() *MachineInstanceTypeSummary {
	this := MachineInstanceTypeSummary{}
	return &this
}

// GetAssigned returns the Assigned field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MachineInstanceTypeSummary) GetAssigned() MachineStatusBreakdown {
	if o == nil || IsNil(o.Assigned.Get()) {
		var ret MachineStatusBreakdown
		return ret
	}
	return *o.Assigned.Get()
}

// GetAssignedOk returns a tuple with the Assigned field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MachineInstanceTypeSummary) GetAssignedOk() (*MachineStatusBreakdown, bool) {
	if o == nil {
		return nil, false
	}
	return o.Assigned.Get(), o.Assigned.IsSet()
}

// HasAssigned returns a boolean if a field has been set.
func (o *MachineInstanceTypeSummary) HasAssigned() bool {
	if o != nil && o.Assigned.IsSet() {
		return true
	}

	return false
}

// SetAssigned gets a reference to the given NullableMachineStatusBreakdown and assigns it to the Assigned field.
func (o *MachineInstanceTypeSummary) SetAssigned(v MachineStatusBreakdown) {
	o.Assigned.Set(&v)
}

// SetAssignedNil sets the value for Assigned to be an explicit nil
func (o *MachineInstanceTypeSummary) SetAssignedNil() {
	o.Assigned.Set(nil)
}

// UnsetAssigned ensures that no value is present for Assigned, not even an explicit nil
func (o *MachineInstanceTypeSummary) UnsetAssigned() {
	o.Assigned.Unset()
}

// GetUnassigned returns the Unassigned field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MachineInstanceTypeSummary) GetUnassigned() MachineStatusBreakdown {
	if o == nil || IsNil(o.Unassigned.Get()) {
		var ret MachineStatusBreakdown
		return ret
	}
	return *o.Unassigned.Get()
}

// GetUnassignedOk returns a tuple with the Unassigned field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MachineInstanceTypeSummary) GetUnassignedOk() (*MachineStatusBreakdown, bool) {
	if o == nil {
		return nil, false
	}
	return o.Unassigned.Get(), o.Unassigned.IsSet()
}

// HasUnassigned returns a boolean if a field has been set.
func (o *MachineInstanceTypeSummary) HasUnassigned() bool {
	if o != nil && o.Unassigned.IsSet() {
		return true
	}

	return false
}

// SetUnassigned gets a reference to the given NullableMachineStatusBreakdown and assigns it to the Unassigned field.
func (o *MachineInstanceTypeSummary) SetUnassigned(v MachineStatusBreakdown) {
	o.Unassigned.Set(&v)
}

// SetUnassignedNil sets the value for Unassigned to be an explicit nil
func (o *MachineInstanceTypeSummary) SetUnassignedNil() {
	o.Unassigned.Set(nil)
}

// UnsetUnassigned ensures that no value is present for Unassigned, not even an explicit nil
func (o *MachineInstanceTypeSummary) UnsetUnassigned() {
	o.Unassigned.Unset()
}

func (o MachineInstanceTypeSummary) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MachineInstanceTypeSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Assigned.IsSet() {
		toSerialize["assigned"] = o.Assigned.Get()
	}
	if o.Unassigned.IsSet() {
		toSerialize["unassigned"] = o.Unassigned.Get()
	}
	return toSerialize, nil
}

type NullableMachineInstanceTypeSummary struct {
	value *MachineInstanceTypeSummary
	isSet bool
}

func (v NullableMachineInstanceTypeSummary) Get() *MachineInstanceTypeSummary {
	return v.value
}

func (v *NullableMachineInstanceTypeSummary) Set(val *MachineInstanceTypeSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableMachineInstanceTypeSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableMachineInstanceTypeSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMachineInstanceTypeSummary(val *MachineInstanceTypeSummary) *NullableMachineInstanceTypeSummary {
	return &NullableMachineInstanceTypeSummary{value: val, isSet: true}
}

func (v NullableMachineInstanceTypeSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMachineInstanceTypeSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
