/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the NicoAPIError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NicoAPIError{}

// NicoAPIError Describes the error response from NCX Infra Controller REST API
type NicoAPIError struct {
	// Source of the error. Only 'nico' is supported
	Source *string `json:"source,omitempty"`
	// Message describing the error
	Message *string `json:"message,omitempty"`
	// Additional data about the error
	Data map[string]interface{} `json:"data,omitempty"`
}

// NewNicoAPIError instantiates a new NicoAPIError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNicoAPIError() *NicoAPIError {
	this := NicoAPIError{}
	return &this
}

// NewNicoAPIErrorWithDefaults instantiates a new NicoAPIError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNicoAPIErrorWithDefaults() *NicoAPIError {
	this := NicoAPIError{}
	return &this
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *NicoAPIError) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NicoAPIError) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *NicoAPIError) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *NicoAPIError) SetSource(v string) {
	o.Source = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *NicoAPIError) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NicoAPIError) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *NicoAPIError) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *NicoAPIError) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NicoAPIError) GetData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NicoAPIError) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *NicoAPIError) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *NicoAPIError) SetData(v map[string]interface{}) {
	o.Data = v
}

func (o NicoAPIError) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NicoAPIError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableNicoAPIError struct {
	value *NicoAPIError
	isSet bool
}

func (v NullableNicoAPIError) Get() *NicoAPIError {
	return v.value
}

func (v *NullableNicoAPIError) Set(val *NicoAPIError) {
	v.value = val
	v.isSet = true
}

func (v NullableNicoAPIError) IsSet() bool {
	return v.isSet
}

func (v *NullableNicoAPIError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNicoAPIError(val *NicoAPIError) *NullableNicoAPIError {
	return &NullableNicoAPIError{value: val, isSet: true}
}

func (v NullableNicoAPIError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNicoAPIError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
