/*
NVIDIA Bare Metal Manager REST API

NVIDIA Bare Metal Manager REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Bare Metal Manager datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateRackRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRackRequest{}

// CreateRackRequest Request body for creating a new expected Rack definition
type CreateRackRequest struct {
	// ID of the Site
	SiteId string `json:"siteId"`
	// Name of the Rack
	Name string `json:"name"`
	// Manufacturer of the Rack
	Manufacturer string `json:"manufacturer"`
	// Model of the Rack
	Model *string `json:"model,omitempty"`
	// Serial number of the Rack
	SerialNumber string `json:"serialNumber"`
	// Description of the Rack
	Description *string `json:"description,omitempty"`
	Location *RackLocation `json:"location,omitempty"`
	// Components to include in the Rack
	Components []RackComponent `json:"components,omitempty"`
}

type _CreateRackRequest CreateRackRequest

// NewCreateRackRequest instantiates a new CreateRackRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRackRequest(siteId string, name string, manufacturer string, serialNumber string) *CreateRackRequest {
	this := CreateRackRequest{}
	this.SiteId = siteId
	this.Name = name
	this.Manufacturer = manufacturer
	this.SerialNumber = serialNumber
	return &this
}

// NewCreateRackRequestWithDefaults instantiates a new CreateRackRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRackRequestWithDefaults() *CreateRackRequest {
	this := CreateRackRequest{}
	return &this
}

// GetSiteId returns the SiteId field value
func (o *CreateRackRequest) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *CreateRackRequest) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *CreateRackRequest) SetSiteId(v string) {
	o.SiteId = v
}

// GetName returns the Name field value
func (o *CreateRackRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateRackRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateRackRequest) SetName(v string) {
	o.Name = v
}

// GetManufacturer returns the Manufacturer field value
func (o *CreateRackRequest) GetManufacturer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Manufacturer
}

// GetManufacturerOk returns a tuple with the Manufacturer field value
// and a boolean to check if the value has been set.
func (o *CreateRackRequest) GetManufacturerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Manufacturer, true
}

// SetManufacturer sets field value
func (o *CreateRackRequest) SetManufacturer(v string) {
	o.Manufacturer = v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *CreateRackRequest) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRackRequest) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *CreateRackRequest) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *CreateRackRequest) SetModel(v string) {
	o.Model = &v
}

// GetSerialNumber returns the SerialNumber field value
func (o *CreateRackRequest) GetSerialNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SerialNumber
}

// GetSerialNumberOk returns a tuple with the SerialNumber field value
// and a boolean to check if the value has been set.
func (o *CreateRackRequest) GetSerialNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SerialNumber, true
}

// SetSerialNumber sets field value
func (o *CreateRackRequest) SetSerialNumber(v string) {
	o.SerialNumber = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateRackRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRackRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateRackRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateRackRequest) SetDescription(v string) {
	o.Description = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *CreateRackRequest) GetLocation() RackLocation {
	if o == nil || IsNil(o.Location) {
		var ret RackLocation
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRackRequest) GetLocationOk() (*RackLocation, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *CreateRackRequest) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given RackLocation and assigns it to the Location field.
func (o *CreateRackRequest) SetLocation(v RackLocation) {
	o.Location = &v
}

// GetComponents returns the Components field value if set, zero value otherwise.
func (o *CreateRackRequest) GetComponents() []RackComponent {
	if o == nil || IsNil(o.Components) {
		var ret []RackComponent
		return ret
	}
	return o.Components
}

// GetComponentsOk returns a tuple with the Components field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRackRequest) GetComponentsOk() ([]RackComponent, bool) {
	if o == nil || IsNil(o.Components) {
		return nil, false
	}
	return o.Components, true
}

// HasComponents returns a boolean if a field has been set.
func (o *CreateRackRequest) HasComponents() bool {
	if o != nil && !IsNil(o.Components) {
		return true
	}

	return false
}

// SetComponents gets a reference to the given []RackComponent and assigns it to the Components field.
func (o *CreateRackRequest) SetComponents(v []RackComponent) {
	o.Components = v
}

func (o CreateRackRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRackRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	toSerialize["name"] = o.Name
	toSerialize["manufacturer"] = o.Manufacturer
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	toSerialize["serialNumber"] = o.SerialNumber
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.Components) {
		toSerialize["components"] = o.Components
	}
	return toSerialize, nil
}

func (o *CreateRackRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
		"name",
		"manufacturer",
		"serialNumber",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateRackRequest := _CreateRackRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateRackRequest)

	if err != nil {
		return err
	}

	*o = CreateRackRequest(varCreateRackRequest)

	return err
}

type NullableCreateRackRequest struct {
	value *CreateRackRequest
	isSet bool
}

func (v NullableCreateRackRequest) Get() *CreateRackRequest {
	return v.value
}

func (v *NullableCreateRackRequest) Set(val *CreateRackRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRackRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRackRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRackRequest(val *CreateRackRequest) *NullableCreateRackRequest {
	return &NullableCreateRackRequest{value: val, isSet: true}
}

func (v NullableCreateRackRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRackRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


