/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the InfrastructureProviderStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InfrastructureProviderStats{}

// InfrastructureProviderStats Provide operational stats for Infrastructure Provider
type InfrastructureProviderStats struct {
	Machine       NullableMachineCountByStatus       `json:"machine,omitempty"`
	IpBlock       NullableIpBlockCountByStatus       `json:"ipBlock,omitempty"`
	TenantAccount NullableTenantAccountCountByStatus `json:"tenantAccount,omitempty"`
}

// NewInfrastructureProviderStats instantiates a new InfrastructureProviderStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInfrastructureProviderStats() *InfrastructureProviderStats {
	this := InfrastructureProviderStats{}
	return &this
}

// NewInfrastructureProviderStatsWithDefaults instantiates a new InfrastructureProviderStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInfrastructureProviderStatsWithDefaults() *InfrastructureProviderStats {
	this := InfrastructureProviderStats{}
	return &this
}

// GetMachine returns the Machine field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InfrastructureProviderStats) GetMachine() MachineCountByStatus {
	if o == nil || IsNil(o.Machine.Get()) {
		var ret MachineCountByStatus
		return ret
	}
	return *o.Machine.Get()
}

// GetMachineOk returns a tuple with the Machine field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InfrastructureProviderStats) GetMachineOk() (*MachineCountByStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.Machine.Get(), o.Machine.IsSet()
}

// HasMachine returns a boolean if a field has been set.
func (o *InfrastructureProviderStats) HasMachine() bool {
	if o != nil && o.Machine.IsSet() {
		return true
	}

	return false
}

// SetMachine gets a reference to the given NullableMachineCountByStatus and assigns it to the Machine field.
func (o *InfrastructureProviderStats) SetMachine(v MachineCountByStatus) {
	o.Machine.Set(&v)
}

// SetMachineNil sets the value for Machine to be an explicit nil
func (o *InfrastructureProviderStats) SetMachineNil() {
	o.Machine.Set(nil)
}

// UnsetMachine ensures that no value is present for Machine, not even an explicit nil
func (o *InfrastructureProviderStats) UnsetMachine() {
	o.Machine.Unset()
}

// GetIpBlock returns the IpBlock field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InfrastructureProviderStats) GetIpBlock() IpBlockCountByStatus {
	if o == nil || IsNil(o.IpBlock.Get()) {
		var ret IpBlockCountByStatus
		return ret
	}
	return *o.IpBlock.Get()
}

// GetIpBlockOk returns a tuple with the IpBlock field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InfrastructureProviderStats) GetIpBlockOk() (*IpBlockCountByStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.IpBlock.Get(), o.IpBlock.IsSet()
}

// HasIpBlock returns a boolean if a field has been set.
func (o *InfrastructureProviderStats) HasIpBlock() bool {
	if o != nil && o.IpBlock.IsSet() {
		return true
	}

	return false
}

// SetIpBlock gets a reference to the given NullableIpBlockCountByStatus and assigns it to the IpBlock field.
func (o *InfrastructureProviderStats) SetIpBlock(v IpBlockCountByStatus) {
	o.IpBlock.Set(&v)
}

// SetIpBlockNil sets the value for IpBlock to be an explicit nil
func (o *InfrastructureProviderStats) SetIpBlockNil() {
	o.IpBlock.Set(nil)
}

// UnsetIpBlock ensures that no value is present for IpBlock, not even an explicit nil
func (o *InfrastructureProviderStats) UnsetIpBlock() {
	o.IpBlock.Unset()
}

// GetTenantAccount returns the TenantAccount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InfrastructureProviderStats) GetTenantAccount() TenantAccountCountByStatus {
	if o == nil || IsNil(o.TenantAccount.Get()) {
		var ret TenantAccountCountByStatus
		return ret
	}
	return *o.TenantAccount.Get()
}

// GetTenantAccountOk returns a tuple with the TenantAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InfrastructureProviderStats) GetTenantAccountOk() (*TenantAccountCountByStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.TenantAccount.Get(), o.TenantAccount.IsSet()
}

// HasTenantAccount returns a boolean if a field has been set.
func (o *InfrastructureProviderStats) HasTenantAccount() bool {
	if o != nil && o.TenantAccount.IsSet() {
		return true
	}

	return false
}

// SetTenantAccount gets a reference to the given NullableTenantAccountCountByStatus and assigns it to the TenantAccount field.
func (o *InfrastructureProviderStats) SetTenantAccount(v TenantAccountCountByStatus) {
	o.TenantAccount.Set(&v)
}

// SetTenantAccountNil sets the value for TenantAccount to be an explicit nil
func (o *InfrastructureProviderStats) SetTenantAccountNil() {
	o.TenantAccount.Set(nil)
}

// UnsetTenantAccount ensures that no value is present for TenantAccount, not even an explicit nil
func (o *InfrastructureProviderStats) UnsetTenantAccount() {
	o.TenantAccount.Unset()
}

func (o InfrastructureProviderStats) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InfrastructureProviderStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Machine.IsSet() {
		toSerialize["machine"] = o.Machine.Get()
	}
	if o.IpBlock.IsSet() {
		toSerialize["ipBlock"] = o.IpBlock.Get()
	}
	if o.TenantAccount.IsSet() {
		toSerialize["tenantAccount"] = o.TenantAccount.Get()
	}
	return toSerialize, nil
}

type NullableInfrastructureProviderStats struct {
	value *InfrastructureProviderStats
	isSet bool
}

func (v NullableInfrastructureProviderStats) Get() *InfrastructureProviderStats {
	return v.value
}

func (v *NullableInfrastructureProviderStats) Set(val *InfrastructureProviderStats) {
	v.value = val
	v.isSet = true
}

func (v NullableInfrastructureProviderStats) IsSet() bool {
	return v.isSet
}

func (v *NullableInfrastructureProviderStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInfrastructureProviderStats(val *InfrastructureProviderStats) *NullableInfrastructureProviderStats {
	return &NullableInfrastructureProviderStats{value: val, isSet: true}
}

func (v NullableInfrastructureProviderStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInfrastructureProviderStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
