/*
NVIDIA Bare Metal Manager REST API

NVIDIA Bare Metal Manager REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NVIDIA Bare Metal Manager datacenters, also referred to as Sites.

API version: 1.0.6
Contact: carbide-dev@exchange.nvidia.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the CreateRackResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRackResponse{}

// CreateRackResponse Response for creating a Rack containing the new rack's ID
type CreateRackResponse struct {
	// ID of the newly created Rack
	Id *string `json:"id,omitempty"`
}

// NewCreateRackResponse instantiates a new CreateRackResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRackResponse() *CreateRackResponse {
	this := CreateRackResponse{}
	return &this
}

// NewCreateRackResponseWithDefaults instantiates a new CreateRackResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRackResponseWithDefaults() *CreateRackResponse {
	this := CreateRackResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CreateRackResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRackResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CreateRackResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CreateRackResponse) SetId(v string) {
	o.Id = &v
}

func (o CreateRackResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRackResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableCreateRackResponse struct {
	value *CreateRackResponse
	isSet bool
}

func (v NullableCreateRackResponse) Get() *CreateRackResponse {
	return v.value
}

func (v *NullableCreateRackResponse) Set(val *CreateRackResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRackResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRackResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRackResponse(val *CreateRackResponse) *NullableCreateRackResponse {
	return &NullableCreateRackResponse{value: val, isSet: true}
}

func (v NullableCreateRackResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRackResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


