FROM golang:1.25 AS builder

ENV GIT_TERMINAL_PROMPT=1
RUN go env -w GOPRIVATE="gitlab-master.nvidia.com"

ARG skipcache=0
COPY . /go/src
WORKDIR /go/src

# Fetch and cache dependencies.  This should mainly be for if we start including other private repos in the build.
RUN --mount=type=secret,id=gitcreds,dst=/root/.netrc go mod download

RUN bash -c 'go fmt ./... > /tmp/gofmt; if grep -q . /tmp/gofmt; then echo "go fmt was unclean on the following files:"; cat /tmp/gofmt; exit 1; fi; rm -f /tmp/gofmt'
RUN go vet ./...
RUN go test ./...

RUN CGO_ENABLED=0 go install -ldflags "-extldflags '-static'"

# Multi-Stage final build
FROM alpine

COPY --from=builder /go/bin/powershelf_manager /opt/powershelf_manager/powershelf_manager

CMD /opt/powershelf_manager/powershelf_manager serve

RUN echo "Success"
