/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
Code is generated
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"net/http"

	"github.com/NVIDIA/ncx-infra-controller-rest/site-manager/pkg/client/clientset/versioned/scheme"
	v1 "github.com/NVIDIA/ncx-infra-controller-rest/site-manager/pkg/crds/v1"
	rest "k8s.io/client-go/rest"
)

type NICoV1Interface interface {
	RESTClient() rest.Interface
	SitesGetter
}

// NICoV1Client is used to interact with features provided by the nico.nvidia.io group.
type NICoV1Client struct {
	restClient rest.Interface
}

func (c *NICoV1Client) Sites(namespace string) SiteInterface {
	return newSites(c, namespace)
}

// NewForConfig creates a new NICoV1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*NICoV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new NICoV1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*NICoV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &NICoV1Client{client}, nil
}

// NewForConfigOrDie creates a new NICoV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *NICoV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new NICoV1Client for the given RESTClient.
func New(c rest.Interface) *NICoV1Client {
	return &NICoV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *NICoV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}

// ForgeLegacyV1Interface provides access to Site resources in the legacy forge.nvidia.io group.
// TODO: remove ForgeLegacyV1Interface and ForgeLegacyV1Client once all site agents have
// migrated from forge.nvidia.io to nico.nvidia.io and forge Sites no longer exist.
type ForgeLegacyV1Interface interface {
	RESTClient() rest.Interface
	SitesGetter
}

// ForgeLegacyV1Client interacts with Sites in the legacy forge.nvidia.io group.
type ForgeLegacyV1Client struct {
	restClient rest.Interface
}

func (c *ForgeLegacyV1Client) Sites(namespace string) SiteInterface {
	return newForgeLegacySites(c, namespace)
}

// NewForgeLegacyForConfig creates a new ForgeLegacyV1Client for the given config.
func NewForgeLegacyForConfig(c *rest.Config) (*ForgeLegacyV1Client, error) {
	config := *c
	if err := setForgeLegacyConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForgeLegacyForConfigAndClient(&config, httpClient)
}

// NewForgeLegacyForConfigAndClient creates a new ForgeLegacyV1Client for the given config and http client.
func NewForgeLegacyForConfigAndClient(c *rest.Config, h *http.Client) (*ForgeLegacyV1Client, error) {
	config := *c
	if err := setForgeLegacyConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &ForgeLegacyV1Client{client}, nil
}

// NewForgeLegacy creates a new ForgeLegacyV1Client for the given RESTClient.
func NewForgeLegacy(c rest.Interface) *ForgeLegacyV1Client {
	return &ForgeLegacyV1Client{c}
}

func setForgeLegacyConfigDefaults(config *rest.Config) error {
	gv := v1.ForgeLegacySchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()
	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
	return nil
}

// RESTClient returns the underlying RESTClient.
func (c *ForgeLegacyV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
