#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name=$(kubectl get pods -n rla | tail -1 | awk '{print $1}')
if [ "$name" = "NAME" ]; then
    echo "rla pod is not running"
    exit 1
fi

kubectl delete pod -n rla $name
